-- Core schema: countries, metrics, and the historical observation fact table.

CREATE TABLE country (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iso2  VARCHAR(2)  NOT NULL,
    iso3  VARCHAR(3),
    name  VARCHAR(120) NOT NULL,
    CONSTRAINT uq_country_iso2 UNIQUE (iso2)
);

CREATE TABLE metric (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_key     VARCHAR(40)  NOT NULL,
    label          VARCHAR(80)  NOT NULL,
    unit           VARCHAR(60),
    indicator_code VARCHAR(40),
    source         VARCHAR(120),
    CONSTRAINT uq_metric_key UNIQUE (metric_key)
);

CREATE TABLE observation (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_id BIGINT           NOT NULL,
    metric_id  BIGINT           NOT NULL,
    obs_year   INT              NOT NULL,
    obs_value  DOUBLE PRECISION NOT NULL,
    CONSTRAINT fk_obs_country FOREIGN KEY (country_id) REFERENCES country (id),
    CONSTRAINT fk_obs_metric  FOREIGN KEY (metric_id)  REFERENCES metric (id),
    CONSTRAINT uq_observation UNIQUE (country_id, metric_id, obs_year)
);

CREATE INDEX idx_obs_metric_year     ON observation (metric_id, obs_year);
CREATE INDEX idx_obs_country_metric  ON observation (country_id, metric_id);
